// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/amyunfei/glassy-sky/internal/admin/domain/postgresql"
	"github.com/amyunfei/glassy-sky/internal/admin/handler"
	"github.com/amyunfei/glassy-sky/internal/admin/service"
)

import (
	_ "github.com/amyunfei/glassy-sky/api"
)

// Injectors from wire.go:

// category handlers
func InitializeCategoryHandlers(repo postgresql.Repository) handler.CategoryHandlers {
	categoryService := service.NewCategoryService(repo)
	categoryHandlers := handler.NewCategoryHandlers(categoryService)
	return categoryHandlers
}

// label handlers
func InitializeLabelHandlers(repo postgresql.Repository) handler.LabelHandlers {
	labelService := service.NewLabelService(repo)
	labelHandlers := handler.NewLabelHandlers(labelService)
	return labelHandlers
}
