// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/amyunfei/glassy-sky/cmd/config"
	"github.com/amyunfei/glassy-sky/internal/admin/domain/postgresql"
	"github.com/amyunfei/glassy-sky/internal/admin/handler"
	"github.com/amyunfei/glassy-sky/internal/admin/infrastructure/token"
	"github.com/amyunfei/glassy-sky/internal/admin/service"
)

import (
	_ "github.com/amyunfei/glassy-sky/api"
)

// Injectors from wire.go:

// user handlers
func InitializeUserHandlers(repo postgresql.Repository, tokenMaker token.Maker, config2 *config.Config) handler.UserHandlers {
	userService := service.NewUserService(repo, tokenMaker, config2)
	userHandlers := handler.NewUserHandlers(userService)
	return userHandlers
}

// category handlers
func InitializeCategoryHandlers(repo postgresql.Repository, options service.CategoryOptions) handler.CategoryHandlers {
	categoryService := service.NewCategoryService(repo, options)
	categoryHandlers := handler.NewCategoryHandlers(categoryService)
	return categoryHandlers
}

// label handlers
func InitializeLabelHandlers(repo postgresql.Repository, options service.LabelOptions) handler.LabelHandlers {
	labelService := service.NewLabelService(repo, options)
	labelHandlers := handler.NewLabelHandlers(labelService)
	return labelHandlers
}
