// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package domain

import (
	"database/sql"
	"time"
)

type Category struct {
	ID        int64
	Name      string
	ParentID  int64
	Color     int32
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}
