// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Category struct {
	ID        int64         `json:"id"`
	Name      string        `json:"name"`
	ParentID  int64         `json:"parent_id"`
	Color     sql.NullInt32 `json:"color"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
	DeletedAt sql.NullTime  `json:"deleted_at"`
}
