// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgresql

import (
	"database/sql"
	"time"
)

type Article struct {
	ID      int64
	Title   string
	Excerpt string
	Content string
	UserID  int64
	// draft, published, archived
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type ArticlesCategory struct {
	ArticleID  int64
	CategoryID int64
}

type ArticlesLabel struct {
	ArticleID int64
	LabelID   int64
}

type Category struct {
	ID        int64
	Name      string
	ParentID  int64
	Color     int32
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type Label struct {
	ID        int64
	Name      string
	Color     int32
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type User struct {
	ID        int64
	Username  string
	Password  string
	Email     string
	Nickname  string
	Avatar    sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}
