// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgresql

import (
	"context"
)

type Querier interface {
	CountArticle(ctx context.Context, title string) (int64, error)
	CountCategory(ctx context.Context, name string) (int64, error)
	CountLabel(ctx context.Context, name string) (int64, error)
	CountUser(ctx context.Context, arg CountUserParams) (int64, error)
	CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteArticle(ctx context.Context, id int64) error
	DeleteCategory(ctx context.Context, id int64) error
	DeleteLabel(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetArticle(ctx context.Context, id int64) (Article, error)
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetLabel(ctx context.Context, id int64) (Label, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListArticle(ctx context.Context, arg ListArticleParams) ([]Article, error)
	ListCategory(ctx context.Context, arg ListCategoryParams) ([]Category, error)
	ListLabel(ctx context.Context, arg ListLabelParams) ([]Label, error)
	ListUser(ctx context.Context, arg ListUserParams) ([]User, error)
	TreeCategory(ctx context.Context) ([]TreeCategoryRow, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateLabel(ctx context.Context, arg UpdateLabelParams) (Label, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
