definitions:
  dto.CreateCategoryRequest:
    properties:
      color:
        type: string
      name:
        type: string
      parentId:
        type: string
    required:
    - color
    - name
    type: object
  dto.CreateCategoryResponse:
    properties:
      color:
        type: string
      createdAt:
        type: string
      id:
        type: string
      name:
        type: string
      parentId:
        type: string
      updatedAt:
        type: string
    type: object
  dto.ModifyCategoryRequest:
    properties:
      color:
        type: string
      id:
        type: string
      name:
        type: string
      parentId:
        type: string
    required:
    - id
    type: object
  dto.SuccessEmptyResponse:
    properties:
      code:
        example: 0
        type: integer
      data:
        example: ""
        type: string
      msg:
        example: success
        type: string
    type: object
info:
  contact: {}
paths:
  /category:
    post:
      parameters:
      - description: 分类信息
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CreateCategoryRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CreateCategoryResponse'
      summary: 创建分类
      tags:
      - 分类信息
  /category/{id}:
    delete:
      parameters:
      - description: 分类id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessEmptyResponse'
      summary: 删除分类
      tags:
      - 分类信息
    put:
      parameters:
      - description: 分类信息
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.ModifyCategoryRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CreateCategoryResponse'
      summary: 修改分类
      tags:
      - 分类信息
swagger: "2.0"
