name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    steps:
    - name: Check out code into the Go module directory
    - uses: actions/checkout@v3

    - name: Test
      run: make test
